{{- if (.Values.data_pvc.enabled) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "ignite.fullname" . }}-persistence-storage-class
provisioner: {{ .Values.data_pvc.provisioner }}
parameters:
{{ toYaml .Values.data_pvc.provisioner_parameters | indent 2 }}
{{- end }}
